# Generated by Django 2.2 on 2019-04-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('prize', models.FloatField()),
                ('quantity', models.IntegerField(max_length=500)),
            ],
        ),
    ]
