# Generated by Django 2.2 on 2019-04-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=30)),
                ('Details', models.CharField(max_length=150)),
                ('Prize', models.FloatField()),
                ('Product_pic', models.ImageField(default='', upload_to='photos/image')),
            ],
        ),
    ]
