# Generated by Django 2.2 on 2019-04-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eno', models.IntegerField()),
                ('Ename', models.CharField(max_length=64)),
                ('Esal', models.FloatField()),
                ('Eaddr', models.CharField(max_length=258)),
            ],
        ),
    ]
