# Generated by Django 2.2 on 2019-04-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhoomapp', '0002_auto_20190424_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_photo',
            new_name='Profile_Pics',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='document',
            new_name='Upload_Resume',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='videofile',
            new_name='Upload_video',
        ),
    ]
