# Generated by Django 2.2 on 2019-04-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhoomapp', '0003_auto_20190424_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Upload_Resume',
        ),
    ]
