# Generated by Django 2.2 on 2019-04-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=64)),
                ('sfees', models.FloatField()),
                ('saddr', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
