# Generated by Django 2.2 on 2019-04-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Profile_pic',
            field=models.ImageField(blank=True, default='', upload_to='photos/image'),
        ),
    ]
